export type Category = "pharmacy" | "grocery" | "personal-care" | "household";

export type Product = {
  id: string;
  name: string;
  category: Category;
  price: number;
  originalPrice?: number;
  unit: string;
  requiresPrescription: boolean;
  inStock: boolean;
  bestseller?: boolean;
  rating: number;
  reviewCount: number;
  description: string;
  details: string[];
  image: string;
};

export const categories: { id: Category; label: string; blurb: string; image: string }[] = [
  {
    id: "pharmacy",
    label: "Pharmacy",
    blurb: "Medicines, verified by our pharmacist",
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800",
  },
  {
    id: "grocery",
    label: "Grocery",
    blurb: "Pantry staples and daily essentials",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
  },
  {
    id: "personal-care",
    label: "Personal care",
    blurb: "Hygiene and wellness for the family",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
  },
  {
    id: "household",
    label: "Household",
    blurb: "Cleaning and everyday supplies",
    image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=800",
  },
];

export const products: Product[] = [
  {
    id: "panadol-500",
    name: "Panadol Extra 500mg",
    category: "pharmacy",
    price: 180,
    unit: "20 tablets",
    requiresPrescription: false,
    inStock: true,
    bestseller: true,
    rating: 4.7,
    reviewCount: 312,
    description: "Fast-acting relief for headache, fever, and body pain.",
    details: ["Paracetamol + Caffeine formula", "Relief within 20 minutes", "For ages 12 and up"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600",
  },
  {
    id: "augmentin-625",
    name: "Augmentin 625mg",
    category: "pharmacy",
    price: 620,
    unit: "10 tablets",
    requiresPrescription: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 96,
    description: "Antibiotic for bacterial infections. Prescription required.",
    details: ["Amoxicillin + Clavulanic acid", "Complete the full course as prescribed", "Store below 25°C"],
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600",
  },
  {
    id: "insulin-glargine",
    name: "Insulin Glargine Pen",
    category: "pharmacy",
    price: 2450,
    unit: "1 pen, 3ml",
    requiresPrescription: true,
    inStock: true,
    rating: 4.9,
    reviewCount: 58,
    description: "Long-acting insulin for diabetes management. Prescription required.",
    details: ["24-hour glucose control", "Keep refrigerated until first use", "Dispensed after pharmacist review"],
    image: "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=600",
  },
  {
    id: "vitamin-c",
    name: "Vitamin C Effervescent",
    category: "pharmacy",
    price: 850,
    originalPrice: 980,
    unit: "20 tablets",
    requiresPrescription: false,
    inStock: true,
    bestseller: true,
    rating: 4.6,
    reviewCount: 204,
    description: "Daily immune support, orange flavour.",
    details: ["1000mg Vitamin C per tablet", "Dissolves in water", "No added sugar"],
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=600",
  },
  {
    id: "calpol-syrup",
    name: "Calpol Syrup (Kids)",
    category: "pharmacy",
    price: 240,
    unit: "60ml bottle",
    requiresPrescription: false,
    inStock: true,
    rating: 4.8,
    reviewCount: 141,
    description: "Gentle fever and pain relief for children.",
    details: ["Strawberry flavour", "Dosage chart on label", "For ages 2 months and up"],
    image: "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=600",
  },
  {
    id: "blood-pressure-monitor",
    name: "Digital BP Monitor",
    category: "pharmacy",
    price: 4200,
    unit: "1 unit",
    requiresPrescription: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 67,
    description: "Automatic arm blood pressure monitor with memory storage.",
    details: ["Stores last 60 readings", "Irregular heartbeat detection", "Includes adapter and cuff"],
    image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=600",
  },
  {
    id: "basmati-rice",
    name: "Super Basmati Rice",
    category: "grocery",
    price: 420,
    unit: "5 kg bag",
    requiresPrescription: false,
    inStock: true,
    bestseller: true,
    rating: 4.9,
    reviewCount: 428,
    description: "Premium long-grain basmati rice, aged for aroma.",
    details: ["Extra-long grain", "Naturally aged 12 months", "Product of Punjab"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600",
  },
  {
    id: "cooking-oil",
    name: "Sunflower Cooking Oil",
    category: "grocery",
    price: 950,
    originalPrice: 1050,
    unit: "5 litre",
    requiresPrescription: false,
    inStock: true,
    rating: 4.4,
    reviewCount: 189,
    description: "Light, cholesterol-free cooking oil.",
    details: ["100% sunflower", "Cholesterol free", "Rich in Vitamin E"],
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
  },
  {
    id: "atta-flour",
    name: "Chakki Fresh Atta",
    category: "grocery",
    price: 680,
    unit: "10 kg bag",
    requiresPrescription: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 256,
    description: "Stone-ground whole wheat flour for soft rotis.",
    details: ["Stone-ground, unbleached", "High fibre content", "Milled fresh weekly"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600",
  },
  {
    id: "tea-leaves",
    name: "Premium Tea Leaves",
    category: "grocery",
    price: 380,
    unit: "400g pack",
    requiresPrescription: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 173,
    description: "Strong, full-bodied black tea blend.",
    details: ["CTC blend", "Rich colour and aroma", "Best with milk"],
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=600",
  },
  {
    id: "dettol-soap",
    name: "Dettol Antibacterial Soap",
    category: "personal-care",
    price: 150,
    unit: "pack of 3",
    requiresPrescription: false,
    inStock: true,
    bestseller: true,
    rating: 4.8,
    reviewCount: 511,
    description: "Protects against 100 illness-causing germs.",
    details: ["Antibacterial formula", "Original scent", "Pack of 3 bars"],
    image: "https://images.unsplash.com/photo-1600857062241-98e5dba7f214?w=600",
  },
  {
    id: "shampoo",
    name: "Anti-Dandruff Shampoo",
    category: "personal-care",
    price: 520,
    unit: "340ml bottle",
    requiresPrescription: false,
    inStock: true,
    rating: 4.3,
    reviewCount: 98,
    description: "Clinically tested to reduce dandruff from the first wash.",
    details: ["Menthol cooling formula", "Dermatologist tested", "For all hair types"],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600",
  },
  {
    id: "toothpaste",
    name: "Fluoride Toothpaste",
    category: "personal-care",
    price: 210,
    unit: "150g tube",
    requiresPrescription: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 267,
    description: "Cavity protection with a fresh mint finish.",
    details: ["Fluoride enriched", "Fresh mint flavour", "Whitens with regular use"],
    image: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600",
  },
  {
    id: "surf-detergent",
    name: "Surf Excel Detergent Powder",
    category: "household",
    price: 640,
    unit: "3 kg",
    requiresPrescription: false,
    inStock: true,
    bestseller: true,
    rating: 4.7,
    reviewCount: 344,
    description: "Removes tough stains in a single wash.",
    details: ["Stain-removal formula", "Works in cold water", "Fresh linen scent"],
    image: "https://images.unsplash.com/photo-1610557892470-55d587fdd5cd?w=600",
  },
  {
    id: "dish-soap",
    name: "Lemon Dish Wash Liquid",
    category: "household",
    price: 280,
    unit: "750ml bottle",
    requiresPrescription: false,
    inStock: true,
    rating: 4.4,
    reviewCount: 132,
    description: "Cuts through grease, gentle on hands.",
    details: ["Grease-cutting formula", "Lemon fragrance", "Gentle on skin"],
    image: "https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=600",
  },
  {
    id: "tissue-rolls",
    name: "Soft Tissue Rolls",
    category: "household",
    price: 460,
    unit: "pack of 6",
    requiresPrescription: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 88,
    description: "3-ply soft tissue for everyday use.",
    details: ["3-ply softness", "Pack of 6 rolls", "Unscented"],
    image: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=600",
  },
];

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}

export function getRelated(product: Product, limit = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}
